sktime/skpro

- skpro/distributions/base.py
- skpro/distributions/normal.py
Migrates some updates from `sktime` to `BaseDistibution`:
* adding `ppf` abstract
* adding `cdf` abstract and default
* fixing bug with referencing non-existing `_method_err_msg` instead of `_method_error_msg`
* removing duplicate implementation of `sample` from `Normal` to use identical base class default
> [ENH] `BaseDistribution` - sync from `sktime`

- skpro/distributions/tests/test_all_distrs.py
The distribution suite test class `TestAllDistributions` did not test any of the distributions in `skpro`, as the `PackageConfig` configuration was not present by inheritance.
This is now fixed, so all distributions are properly tested.
> [BUG] fix distribution suite test class missing package config

- skpro/distributions/__init__.py
- skpro/distributions/base.py
- skpro/distributions/mixture.py
- skpro/tests/test_all_estimators.py
Implements mixture of distributions.
Towards https://github.com/sktime/skpro/issues/22, and required for ensemble regressor.
Also adds a default implementation for `ppf` in the `BaseDistribution`, using the bisection method to invert a `cdf`, if present.
> [ENH] mixture of distributions

- examples/custom_model.py
- examples/parametric/hyperparameters.py
- examples/parametric/simple.py
- examples/simple.py
- skpro/workflow/manager/data.py
This PR removes imports of deprecated `load_boston` loader from `sklearn` from the legacy modules. This is required to upgrade `sklearn` to 1.2.0 or higher.
> [MNT] remove deprecated `load_boston` loader from `sklearn`

- skpro/distributions/empirical.py
- skpro/distributions/tests/test_all_distrs.py
- skpro/utils/index.py
Adds a test to the distribution suite tests ensuring that they subset appropriately via `loc` and `iloc`, and satisfy common interface expectations on the resulting object and index.
Also fixes a bug in subsetting of `Empirical` that was highlighted by these tests.
> [ENH] add test for subsetting distributions

- skpro/distributions/base.py
- skpro/distributions/empirical.py
This PR turns off sorting in `groupby` calls. Towards #40.
> [ENH] turn off sorting in `groupby`-s

- skpro/regression/base/_base.py
- skpro/regression/bootstrap.py
This PR adds a bootstrap probabilistic regressor that turns any sklearn regressor into a probabilistic one via the classical bootstrap.
Also makes a minor upgrade to the `BaseProbaRegressor` class: if `_predict` is not implemented, it defaults to `_predict_proba(X).mean()`.
> [ENH] adds bootstrap probabilistic regressor

- skpro/distributions/base.py
- skpro/metrics/base.py
- skpro/registry/__init__.py
- skpro/registry/_lookup.py
- skpro/registry/_tags.py
- skpro/regression/base/_base.py
- skpro/tests/test_all_estimators.py
This PR adds a registry module, with lookup and tag register.
Contents:
* a tag register in `registry._tags`. The current register from `test_all_estimators` is migrated there.
* a `_lookup` module with `all_objects` and `all_tags` lookup methods, as in `sktime`.
* populates `object_type` tag for all objects in `skpro`
In contrast to `sktime`, no base class registry is added, as this is now handled via the tag system and the `object_type` tag.
> [ENH] registry module with lookup and tag register

- .github/workflows/test.yml
- extension_templates/regression.py
- setup.cfg
- skpro/base/__init__.py
- skpro/benchmarking/evaluate.py
- skpro/datatypes/_check.py
- skpro/datatypes/_common.py
- skpro/datatypes/_convert.py
- skpro/datatypes/_examples.py
- skpro/datatypes/_registry.py
- skpro/distributions/base.py
- skpro/distributions/empirical.py
- skpro/distributions/normal.py
- skpro/distributions/tests/__init__.py
- skpro/distributions/tests/test_all_distrs.py
- skpro/metrics/_coerce.py
- skpro/metrics/base.py
- skpro/registry/_lookup.py
- skpro/utils/_maint/_show_versions.py
- skpro/utils/_maint/tests/test_show_versions.py
- skpro/utils/validation/_dependencies.py
This PR replaces some erroneous references to `sktime` with `skpro`:
* docstring references to classes
* copyright - this should be accompanied with a credit to `sktime` in prominent locations, or where copy-paste has taken place
* `show_versions` utility
* code coverage target
The rst documentation is untouched for now, this will be a later effort.
> [DOC] replace leftover `sktime` references in docstrings and utilities with `skpro`

- skpro/regression/residual.py
This PR fixes an unreported bug, a missing `np.abs` in `ResidualDouble`.
Acknowledging that the estimator does not have all its features migrated yet, but the abs operator was missing.
Tests did not catch this as this would just result in bad predictions.
> [BUG] fix missing `np.abs` in `ResidualDouble`

- skpro/distributions/t.py
Referencing PR from `sktime` https://github.com/sktime/sktime/pull/5050.
Add student's t-distribution.
No
the PR topic is related to enhancement, CI/CD, maintenance, documentation, or a bug.
> [ENH] Student's t-distribution

- skpro/registry/_tags.py
- skpro/regression/base/_base.py
- skpro/regression/compose/__init__.py
- skpro/regression/compose/_pipeline.py
Implements https://github.com/sktime/skpro/issues/29 - a simple pipeline compatible with `sklearn` transformers.
> [ENH] pipeline

- skpro/distributions/base.py
- skpro/distributions/laplace.py
- skpro/distributions/normal.py
- skpro/distributions/t.py
- skpro/distributions/tests/test_base_default_methods.py
Copied from this PR from sktime https://github.com/sktime/sktime/pull/5176
Refactors the `_get_bc_params` function in the `BaseDistribution` class.
No.
the PR topic is related to enhancement, CI/CD, maintenance, documentation, or a bug.
> [ENH] Refactor of BaseDistribution and descendants - generalised distribution param broadcasting in base class

- skpro/regression/residual.py
This completes the implementation of `ResidualDouble`, in parts relying on the set of distributions implemented now - in parts, thanks to @Alex-JG3! 
The functionality is now on par with the `skpro` version 1 features and upgraded to the new interface.
A comprehensive docstring with a formal summary of the algorithm has also been added.
> [ENH] residual double regressor - feature complete implementation

- skpro/regression/base/_base.py
This adds a default for `predict` if only interval/quantile predictions are possible, but not full distribution predictions.
> [ENH] enable default for `predict` in probabilistic regressors if only interval predictions are possible

- .github/PULL_REQUEST_TEMPLATE.md
This PR updates the PR template - which previously was a copy of `skbase`'s - to a template specific to `skpro`.
It should be noted that this links to documentation folders which do not exist yet, but will be created soon.
> [DOC] PR template update

- skpro/utils/plotting.py
- skpro/utils/tests/test_plots.py
This PR fixes an unreported bug with `test_plot_crossplot_interval` - it would fail for interval predictions as internally the input would be incorrectly identified as a distribution - as the check checks whether a `quantiles` method is present, and `DataFrame`-s have this too, not just distributions.
This is rectified by an explicit type check.
Tests for the input case are also added.
> [BUG] fix `test_plot_crossplot_interval` for interval predictions

- skpro/metrics/__init__.py
This PR adds a forgotten `__init__` export of `SquaredDistrLoss` - due ot this, previously, the metric was neither accessible to the registry, nor tested.
> [BUG] add forgotten `__init__` export of `SquaredDistrLoss`

- skpro/utils/plotting.py
Fixes a minor typo in `plot_crossplot_std` docstring
> [DOC] fixing typo in `plot_crossplot_std` docstring

- skpro/utils/plotting.py
- skpro/utils/tests/test_plots.py
This PR fixes an unreported bug where `plot_crossplot_std` would crash for for a `predict_var` return (as opposed to a full distributional prediction).
This is fixed, and a test is added.
> [BUG] fix `plot_crossplot_std` for `predict_var` return

- skpro/distributions/empirical.py
This fixes a bug in the empirical distribution's subsetting routine if no row subsetting takes place, but column subsetting does.
In this case, the variable `weights_subset` would not be set but is referenced later.
Not sure why the tests didn't catch this, the subsetting test should test this case.
> [BUG] fix subsetting of empirical distribution if no row subsetting takes place

- skpro/distributions/empirical.py
Sometimes the `Empirical` `energy` calculation crashes, the reason as it seems is that `numpy` sometimes interprets `array[1::-1]` as returning `array[1], array[0]` rather than `array[-1], array[-2], .., array[1]` which is really odd, either way, this is now replaced by safer syntax.
> [BUG] avoid `numpy` strangeness in `energy` calculation in `Empirical`

- skpro/regression/residual.py
This fixes an unreported bug in `ResidualDouble` where `fit` would break if the default residual estimator is used.
This was due to the non-underscore parameter being referenced instead of the underscored one.
> [BUG] in `ResidualDouble`, fix out-of-sample residual prediction if residual estimator is default

- skpro/regression/bootstrap.py
- skpro/regression/residual.py
- skpro/utils/numpy.py
`sklearn` estimators wrapped in `BootstrapRegressor` or `ResidualDouble` complain if uni-output target variables are passed as 2D column array, not 1D.
In order to still allow multioutput regressors but avoid the warning, this PR introduces a utility and applies it to flatten uni-output 2D arrays (column vectors) to 1D, but leave multivariate 2D arrays untouched.
> [ENH] pass targets to `sklearn` as 1D and not 2D if univariate column vector

- .github/workflows/test.yml
- pyproject.toml
This PR conducts minor maintenance on the CI and dependency set.
* unused soft dependencies are removed from `all_extras`. `ngboost` and `distfit` are added in anticipation of estimators based on these.
* it is ensured that `all_extras` are available when testing the tutorial notebooks
> [MNT] update `all_extras` dependency set and notebook CI

- skpro/datatypes/_proba/_registry.py
- skpro/datatypes/_registry.py
- skpro/datatypes/_table/_registry.py
- skpro/distributions/base.py
- skpro/distributions/mixture.py
- skpro/metrics/base.py
- skpro/metrics/metrics.py
This PR addresses various deprecation warnings:
* deprecation of `axis` arg in `pd.DataFrame.groupby`
* deprecation of `float` coercion of single-element `pd.Series`
* deprecation of `pd.DataFrame.applymap` in favour of `map`
* incorrect use of string escape parameters in legacy code
* fixing some linting issues in legacy code
> [MNT] various deprecation fixes

- skpro/registry/__init__.py
This PR adds a public export of the `all_tags` utility to the `registry` module.
It already was present and fully functional, but not exported.
> [ENH public `all_tags` utility

- skpro/datatypes/_check.py
Removes some typing that prevents the readthedocs build.
> [MNT] remove types from `typing-extensions`

- skpro/utils/__init__.py
- skpro/utils/estimator_checks.py
- skpro/utils/validation/_dependencies.py
This adds a `check_estimator` utility for checking implemented objects against their type specific contracts.
> [ENH] `check_estimator` utility

- .github/workflows/test.yml
- conftest.py
- setup.cfg
- skpro/tests/test_all_estimators.py
- skpro/utils/git_diff.py
This PR introduces the differential testing from `sktime` to the PR CI, to test only estimators from modules that have changed.
This does not affect the release CI, which runs the tests for all estimators in `sktime`.
> [MNT] Differential testing of estimators

- .github/workflows/wheels.yml
This changes the pypi wheels publish credentials from user name and password to skpro specific API token.
> [MNT] publish using API token

- .all-contributorsrc
- docs/source/changelog.rst
* finalized release notes
* version bump is not necessary, has happened previously
> Release 2.0.0

- skpro/tests/test_all_estimators.py
This PR addresses deprecation (and removal in `skbase 0.6.0`) of `skbase.testing.utils.deep_equals`, by moving imports to the new location of the same module.
> [MNT] address deprecation of `skbase.testing.utils.deep_equals`

- .github/workflows/wheels.yml
This PR simplifies the test of wheels for release, and removes the dependency on miniconda which seems to have issues with python 3.12.
> [MNT] simplify wheels test for release

- docs/source/conf.py
Attempts to fix https://github.com/sktime/skpro/issues/122 by pointing the json switcher to the GitHub location.
Hypothesis: a broken `json` got uploaded to readthedocs, and it will prevent upload of a correct version.
> [MNT] point readthedocs `json` switcher variable to GitHub

- skpro/utils/plotting.py
This fixes some broken docstrings in `plotting` as sphinx needs "math" environments to parse TeX.
> [DOC] fix math in `plotting` docstrings

- skpro/registry/_tags.py
- skpro/regression/base/_base.py
This PR connects the `datatypes` module with the base class layer, and enables use of `numpy` arrays and `pd.Series` as possible inputs for `X` and `y`.
Further, tags `X_inner_mtype` and `y_inner_mtype` are introduced to allow use of different types internally.
This is also an architectural necessity (in the abstract sense) for allowing both `pandas` and `polars` later on, compare https://github.com/sktime/sktime/issues/5423
> [ENG] probabilistic regressors - input checks and support for more input types

- extension_templates/regression.py
This PR improves the probabilistic tabular regressor extension template by:
* adding useful boilerplate code for generating expected indices of output
* explaining that at least one of the proba methods should be implemented, and providing templates for the other proba methods (not just `_predict_proba`)
> [ENH] improved probabilistic tabular regressor extension template

- skpro/tests/test_all_estimators.py
- skpro/utils/estimator_checks.py
This PR properly integrates `TestAllEstimators` and `TestAllRegressors` with the `check_estimator` utility and fixes. These were so far not connected due to dependencies on the test scenarios which now have been added (and a bug in `scitype` name resolution).
The integration happens in three places:
* `TestAllEstimators` now inherits from `skbase` `QuickTester` to allow command line testing
* `check_estimator` now runs `TestAllEstimators` for estimators
* `TestAllRegressor` integration with `check_estimator` is fixed, the scitype string was erroneously `"regressor"` instead of, correctly, `"regressor_proba"`.
> [ENH] integrate `check_estimator` with `TestAllEstimators` and `TestAllRegressors` for python command line estimator testing

- extension_templates/regression.py
Fixes some typos in the regression extension template.
Inaccurately, the columns of `y` were confusingly referred to as the index. This has been corrected.
> [DOC] typo fixes in regression extension template

- skpro/tests/test_all_estimators.py
- skpro/tests/test_switch.py
- skpro/utils/validation/_dependencies.py
This PR brings the conditional testing framework in a line with `sktime` logic:
* only those objects are tested whose modules or base class modules have changed
* estimators whose dependencies are not present are not tested
* adds mirror of fix https://github.com/sktime/sktime/pull/5473
> [ENH] improved conditional testing

- skpro/distributions/tests/test_all_distrs.py
- skpro/regression/tests/test_all_regressors.py
This PR fixes the test fixture generation logic, and fixes https://github.com/sktime/skpro/issues/128.
The problem was that some `TestAll...` classes were inheriting from `skbase` `FixtureGenerator` and not from the `skpro` fixture generator `FixtureGenerator` (from `test_all-estimators`) which overrides `_all_objects` to test only incrementally, or objects with available dependencies.
> [BUG] fix test fixture generation logic

- skpro/registry/_lookup.py
This PR fixes an unreported bug in `all_objects` when both the `object_type` and `filter_tags` were provided.
In this case, only the `filter_tags` filter would be applied.
> [BUG] fix retrieval in `all_objects` if `filter_tags` is provided

- AUTHORS.rst
The authors file still had 2018 content in it, this has been updated to reflect the current status.
> [DOC] update `AUTHORS.rst` file

- skpro/regression/base/_base.py
In proba regressors, if `X: pd.DataFrame` and `y: np.ndarray` are passed, and both are internally converted to `pandas`, `y` will acquire an index which should equal that of `X`.
However, currently `y` alsways gets a `RangeIndex`.
This PR rectifies handling in this combination case.
Test coverage is provided by https://github.com/sktime/skpro/pull/145.
> [ENH] in proba regressors, ensure correct index treatment if `X: pd.DataFrame` and `y: np.ndarray` are passed

- skpro/regression/bootstrap.py
- skpro/regression/compose/_pipeline.py
- skpro/regression/mapie.py
- skpro/regression/residual.py
- skpro/utils/sklearn.py
This PR ensures that `sklearn` wrappers str-coerce columns of `pd.DataFrame` before passing them to `sklearn`, avoiding failures due to mixed column types.
Test coverage is provided in https://github.com/sktime/skpro/pull/145
> [ENH] `sklearn` wrappers to str-coerce columns of `pd.DataFrame` before passing

- skpro/datatypes/_adapter/polars.py
- skpro/datatypes/_table/_check.py
- skpro/datatypes/_table/_examples.py
- skpro/datatypes/tests/test_check.py
This PR adds `n_features` and `feature_names` metadat field for data table mtypes - similar to the attributes of the same name in `sklearn`.
This will be useful for cleaner input/output queriability in a variety of places, and further `sklearn` compatibility.
Similar to https://github.com/sktime/sktime/pull/5596 (for time series)
> [ENH] `n_features` and `feature_names` metadata field for table mtypes

- skpro/datatypes/__init__.py
- skpro/datatypes/_check.py
- skpro/datatypes/tests/test_check.py
- skpro/distributions/tests/test_all_distrs.py
- skpro/regression/base/_base.py
- skpro/regression/tests/test_all_regressors.py
This PR brings the datatypes checkers to the same input/output format as https://github.com/sktime/sktime/pull/5510.
Main changes:
* `check_is_mtype` gets an option to return multiple error messages in same format as `check_is_scitype`, with a deprecation for this as the default if multiple `mtypes` to check against are passed.
* added `check_is_error_msg` for streamlined generation of input check error messages
* placeholder error message in `BaseRegressorProba` is replaced by `check_is_error_msg` return
This also introduces deprecation warnings for 2.3.0.
> [ENH] `check_is_mtype` dict type return, improved input check error messages in `BaseRegressorProba`

- skpro/regression/base/_base.py
This PR cleans up some copy-paste leftovers in `BaseProbaRegressor` that could have led to bugs:
* stray `index`, `columns` argument, these are not used and likely copy-paste artefacts from `BaseDistribution`
* there was a superfluous convert in `predict_proba` - this could have led to errors, but did not, as it defaulted to the identity transform
* minor refactor - made checker functions pure, `self` write moved to `fit`
> [ENH] clean up copy-paste leftovers in `BaseProbaRegressor`

- skpro/distributions/adapters/__init__.py
- skpro/distributions/adapters/scipy/__init__.py
- skpro/distributions/adapters/scipy/_empirical.py
- skpro/distributions/adapters/scipy/tests/__init__.py
- skpro/distributions/adapters/scipy/tests/test_scipy_adapters.py
- skpro/distributions/empirical.py
This PR adds an adapter from lists of `scipy` `rv_discrete` to `skpro` `Empirical`.
This adapter will be useful in interfacing `statsmodels` models that return lists of discrete `rv_discrete` distributions to represent tabular distribution objects.
Also makes minor corrections to the `Empirical` docstring, and removes a stray line.
> [ENH] adapter from `scipy` `rv_discrete` to `skpro` `Empirical`

- skpro/registry/__init__.py
- skpro/registry/_scitype.py
- skpro/registry/tests/test_scitype.py
- skpro/tests/test_class_register.py
- skpro/tests/test_switch.py
- skpro/utils/estimator_checks.py
This PR brings registries and test logic on par with `sktime` state:
* `scitype` inference utility, can be used to coerce tag to single string
* test class registry, accessible via `get_test_classes_for_obj`
* `check_estimator` is refactored using the above
* `run_test_for_class` is updated with a condition that estimators are always tested if any covering test class changes
> [ENH] scitype inference utility, test class register, test class test condition

- .github/.codecov.yml
Partially addresses https://github.com/sktime/skpro/issues/164 by adding a `codecov.yml` that ensures CI does not fail on low CI.
This is not fully satisfactory, but takes into account that repoted coverage underestimates actual, due to incremental testing.
> [ENH] adding `codecov.yml` and turning coverage reports informational

- skpro/regression/adapters/__init__.py
- skpro/regression/adapters/sklearn/__init__.py
- skpro/regression/adapters/sklearn/_sklearn_proba.py
Adds an adapter for `sklearn` probabilistic regressors, such as `BayesianRidge` or `GaussianProcessRegressor`.
This adapter can later be used for concrete shorthands.
Internally - like sklearn - the adapter assumes a `predict` interface with `return_std` and a nomal predictive distribution.
> [ENH] adapter for `sklearn` probabilistic regressors

- skpro/regression/adapters/sklearn/_sklearn_proba.py
This PR adds tags in `SklearnProbaReg`, otherwise one of the tests complains.
Should not matter due to inheritance, and odd that it did not complain when merged.
> [ENH] add tags to `SklearnProbaReg`

- skpro/distributions/base.py
- skpro/distributions/normal.py
- skpro/utils/pandas.py
This PR handles deprecation of `DataFrame.applymap`, by replacing instances with a version-conditional call.
Additionally, also fixes a minor, unrelated docstring typo.
> [MNT] handle deprecation of `pandas.DataFrame.applymap`

- skpro/datatypes/_adapter/polars.py
- skpro/utils/deep_equals/_deep_equals.py
Handles deprecations from `polars`:
* `sum(axis=1)` being replaced by `sum_horizontal`
* `frame_equal` being renamed to `equals`
> [MNT] handle `polars` deprecations

- skpro/tests/test_switch.py
This PR fixes incorrect test switching logic in `run_test_for_class`, which was incorrectly looking for base classes in `sktime`, not `skpro`.
> [BUG] fix incorrect test switch logic

- skpro/regression/base/_base.py
This switches explicit inspection of columns to use the `"feature_names"` metadata field from `datatypes` checks.
> [ENH] in `BaseRegressorProba`, use `"feature_names"` metadata field to store feature names

- extension_templates/regression.py
- skpro/base/_base.py
- skpro/distributions/qpd.py
- skpro/registry/_tags.py
- skpro/regression/bootstrap.py
- skpro/regression/cyclic_boosting.py
- skpro/regression/mapie.py
- skpro/regression/multiquantile.py
This PR:
* adds authors and maintainers tags, bringing the packaging tags on par with `sktime`
* the tags are also filled for contributed estimators
* documents probabilistic regressor tags in the extension template from regressors. These were missing previously.
> [ENH] author and maintainer tags, tags documented in regressor extension template

- skpro/regression/adapters/sklearn/_sklearn_proba.py
- skpro/regression/linear/_sklearn.py
This PR fixes API non-compliances in the `sklearn` variance prediction adapters, uncovered by https://github.com/sktime/skpro/pull/189:
* `sklearn` `ARDRegressor` fails with `X: pd.DataFrame` on `predict` with `return_std=True` https://github.com/scikit-learn/scikit-learn/issues/28310
* `skpro` `SklearnProbaReg.predict` returned `np.ndarray` even if `y` in `fit` was `pd.DataFrame`
> [BUG] fix API non-compliance in `sklearn` variance prediction adapter

- skpro/distributions/tests/test_all_distrs.py
- skpro/regression/tests/test_all_regressors.py
This PR adds a skip for failures of `CyclicBoosting` and QPD objects on main, until failures in #189 are resolved.
The PR resolving the failures should remove the skips again.
> [MNT] skip `CyclicBoosting` and QPD tests until #189 failures are resolved

- skpro/distributions/base.py
- skpro/metrics/tests/test_distr_metrics.py
This PR fixes an unreported bug where the fallback Monte Carlo approximation for `pdfnorm` was not working, and adds semi-direct tests through the sqared norm metric.
> [BUG] fix fallback for `pdfnorm` method, add metrics to tests

- docs/source/api_reference.rst
- docs/source/api_reference/metrics.rst
- skpro/distributions/base.py
- skpro/metrics/__init__.py
- skpro/metrics/base.py
- skpro/metrics/survival/__init__.py
- skpro/metrics/survival/_c_harrell.py
- skpro/metrics/survival/_spll.py
- skpro/metrics/survival/tests/__init__.py
- skpro/metrics/survival/tests/test_c_harrell.py
- skpro/metrics/tests/test_distr_metrics.py
- skpro/registry/_tags.py
This PR adds framework support for survival prediction metrics, and test coverage.
It also adds two metrics for survival predictions, as proof-of-concept, and for testing the framework.
* the survival process log-loss - a proper scoring rule for survival predictions
* Harrell's C-index
Survival prediction metrics use the `BaseProbaMetric` or `BaseDistrMetric` as base class, and differ only in that they may optionally take a `pd.DataFrame` of censoring indicators as argument `C_true` in `evaluate` or `evaluate_by_index`.
An implementer of `_evaluate_by_index` of a survival metric will have to cope with the cases of `C_true=None` and `C_true: pd.DataFrame`.
Metrics that make use of `C_true` are labelled with the `capability_survival` tag.
The above design ensures that:
* non-survival …
> [ENH] survival prediction metrics - framework support and tests, SPLL, Harrell C

- README.md
- docs/source/api_reference/regression.rst
This PR updates the README to projected 2.2.0 state:
* "features" section with reference to popuar third party packages such as `cyclic_boosting`
* estimator/object type table in features section
* reference to time-to-event/survival task
Minor fixes:
* regression API page had an incorrect header, fixed
> [DOC] README update

- skpro/metrics/base.py
- skpro/metrics/tests/test_distr_metrics.py
- skpro/tests/test_class_register.py
This PR migrates tests of distribution prediction metrics to an `skbase` class.
Also generalizes the test for censored ground truth.
> [ENH] migrate tests of distribution prediction metrics to `skbase` class

- skpro/distributions/empirical.py
Towards #212, this makes the `Empirical` distribution compatible with multi-index rows.
Mirror of https://github.com/sktime/sktime/pull/6066
> [ENH] make `Empirical` distribution compatible with multi-index rows

- docs/source/conf.py
A docs bug discussed on Discord. The source link is pointing to the non-existent latest branch instead of main. I think this would be the simplest solution, though you would have to merge to see if it works. A relevant part in sktime docs for more clarification  https://github.com/sktime/sktime/blob/9838adfed3ebd5fcf42805ddd6448606c2743585/docs/source/conf.py#L33
> [MNT] Fix broken api source links in latest docs version

- skpro/distributions/base.py
- skpro/distributions/tests/test_all_distrs.py
This PR adds a `__len__` dunder to `BaseDistribution`, and a test for `len` and `shape`.
> [ENH] add `len` of `BaseDistribution`, test `shape`, `len`, indices

- skpro/tests/scenarios/scenarios_regressor_proba.py
This PR refactors test scenario creation to be lazy rather than on module load.
Currently, the data for test scenarios is created on module load and is persisted as module variables, which may increase test collection time and memory usage. The status quo also creates a risk for side effects to which `pandas` objects are prone.
This PR migrates the architecture to the same pattern that `pytest` fixtures use, where concrete objects are only created when the scenario is loaded. The change also ensures that a new object is created each time the fixture is requested, avoiding side effects from mutating the single reference.
Same as https://github.com/sktime/sktime/pull/6278, for `skpro`.
> [ENH] refactor test scenario creation to be lazy rather than on module load

- docs/source/api_reference/survival.rst
- pyproject.toml
- skpro/survival/adapters/_common.py
- skpro/survival/adapters/lifelines.py
- skpro/survival/adapters/sksurv.py
- skpro/survival/additive/__init__.py
- skpro/survival/additive/_aalen_lifelines.py
- skpro/survival/aft/__init__.py
- skpro/survival/aft/_aft_lifelines_weibull.py
- skpro/survival/coxph/__init__.py
- skpro/survival/coxph/_coxph_lifelines.py
Adds an adapter to `lifelines`, exposing array-like survival functions as `Empirical` distributions in `predict_proba`.
Adds all models from `lifelines` which are capable of full distributional predictions:
* `AalenAdditiveFitter`
* `CoxPHFitter`
* `WeibullAFTFitter`
Remaining AFT fitters require distributions not yet merged.
> [ENH] adapter to `lifelines`, most distributional survival regressors interfaced

- skpro/distributions/lognormal.py
It appears `_get_bc_params` got accidentally copied from the base class to `LogNormal`.
This PR removes the redundant copy.
> [ENH] remove stray `_get_bc_params` from `LogNormal`

- skpro/distributions/qpd_empirical.py
This PR adds a mathematical description in the docstring of `QPD_Empirical`.
The docstring also explains why the distribution is quantile parameterized, and its relation to `Empirical`.
A review would be appreciated, @Ram0nB, @setoguchi-naoki, @felixwick - I also hope (and would appreciate a check) for typos in the math.
FYI @vascosch92, as this is an example where two formal objects:
* are equivalent if considered without parameterization
* but not equivalent if considered together with the parameterization
and the more general question what the class/design principle should be here. Compare `Fibonacci` vs `OEIS(n)` object. Also relates to the "multiple names" discussion in https://github.com/VascoSch92/sequentium/issues/49, I am currently of the opinion that different class names should …
> [DOC] docstring with mathematical description for `QPD_Empirical`

- skpro/distributions/qpd.py
Adds some missing capability tags to the Johnson QPD distributions.
Includes minor improvements to the docstring.
FYI @setoguchi-naoki, @felixwick - I think these were simply missing, added them.
> [ENH] Johnson QP-distributions - add some missing capability tags

- docs/source/api_reference/distributions.rst
- skpro/distributions/__init__.py
- skpro/distributions/fisk.py
- skpro/survival/ensemble/_survforest_sksurv.py
This PR adds a Fisk distribution aka log-logistic distribution.
Required for interfacing log-logistic AFT from `lifelines`.
> [ENH] Fisk distribution aka log-logistic distribution

- docs/source/api_reference/survival.rst
- skpro/survival/aft/__init__.py
- skpro/survival/aft/_aft_lifelines_fisk.py
- skpro/survival/aft/_aft_lifelines_lognormal.py
Adds the log-logistic/Fisk AFT model from `lifelines`.
Also fixes a bug with the recently added log-normal model that invoked the wrong estimator (see https://github.com/sktime/skpro/pull/258).
Closes #250
> [ENH] log-logistic/Fisk AFT model from `lifelines`

- docs/source/changelog.rst
This PR fixes a small typo in a link in the changelog.
> [DOC] fix typo in changelog link

- skpro/survival/aft/_aft_lifelines_fisk.py
Fixes some copy-paste typos in the Fisk AFT docstring.
> [DOC] typo fixes in Fisk AFT docstring

- docs/source/changelog.rst
This PR fixes some minor typos in the changelog.
> [DOC] fix minor typos in the changelog

- .github/workflows/test.yml
This PR moves GHA runners consistently to `ubuntu-latest`, `windows-latest`, `macos-13`.
`macos-latest` is failing with python 3.8 and 3.9 recently, and `macos-14` = `macos-latest` has half the memory of `macos-13`.
> [MNT] move GHA runners consistently to `ubuntu-latest`, `windows-latest`, `macos-13`

- .github/workflows/test.yml
- .github/workflows/wheels.yml
Sets the macos runner for release workflow to `macos-13`.
Same as #272, for the release workflow.
> [MNT] set macos runner for release workflow to `macos-13`

- skpro/distributions/base/_base.py
- skpro/distributions/tests/test_proba_basic.py
- skpro/registry/_tags.py
This adds `at` and `iat` subsetters for distributions.
If a scalar version of the distribution is implemented, produces a scalar distribution at that entry.
> [ENH] `at` and `iat` subsetters for distributions

- skpro/distributions/base/_base.py
- skpro/distributions/tests/test_proba_basic.py
This PR adds convenience sugar to coerce `index` and `columns` to `pd.Index`.
Does not impact existing functionality.
Tests are added for the new call cases.
> [ENH] probability distirbutions: convenience feature to coerce `index` and `columns` to `pd.Index`

- skpro/distributions/base/_base.py
- skpro/distributions/fisk.py
- skpro/distributions/laplace.py
- skpro/distributions/logistic.py
- skpro/distributions/lognormal.py
- skpro/distributions/t.py
- skpro/distributions/weibull.py
Adds scalar test cases for probability distributions which support scalar polymorphism to cover that type case.
Includes bugfixes for bugs detected through this:
* Weibull distribution `pdf`, `log_pdf`, `cdf` in scalar case
* default implementation of `_energy` in scalar case
> [ENH] scalar test cases for probability distributions

- README.md
- docs/source/changelog.rst
By accident, the dates of all 2024 hangelogs were given as 2023.
This has been fixed.
> [DOC] correcting 2024 changelog dates

- .all-contributorsrc
This adds some contributors from recent PR to the `all-contributorsrc` file who forgot to add themselves: @an20805, @duydl, @sukjingitsit
> [DOC] add missing contributors - @an20805, @duydl, @sukjingitsit

- skpro/distributions/empirical.py
The `Empirical` distribution would produce `pd.Index` of tuples instead of `pd.MultiIndex` in some methods, causing failures in https://github.com/sktime/sktime/pull/6052.
This PR fixes that - mirror of https://github.com/sktime/sktime/pull/6341
> [ENH] fix `Empirical` index to be `pd.MultiIndex` for hierarchical data index

- .binder/Dockerfile
The `binder` environment does not seem to work - this PR adds a `binder` docker specification with an editable install of `main`.
> [MNT] fix binder environment

- skpro/tests/_config.py
- skpro/tests/_config_test_dummy.py
- skpro/tests/test_switch.py
- skpro/tests/tests/__init__.py
- skpro/tests/tests/test_test_utils.py
- skpro/utils/git_diff.py
This speeds up collection of differential tests through caching, and adds a test condition if a relevant `pyproject` dependency line changes.
Mirrors https://github.com/sktime/sktime/pull/6357 for the caching extension.
> [ENH] faster collection of differential tests through caching, test if pyproject change

- skpro/distributions/adapters/statsmodels/_empirical.py
- skpro/survival/coxph/_coxph_statsmodels.py
This PR fixes an unreported bug where `CoxPH` interfaced `statsmodels` incorrectly.
In `statsmodels`, `status=1` means uncensored, and `status=0` means censored. In `sktime`, `C=1` means censored, and `C=0` means uncensored.
This flipping was missing in the adapter.
> [BUG] fix `CoxPH` handling of `statsmodels` `status` variable

- skpro/distributions/empirical.py
Towards #283.
* adds a scalar mode to the `Empirical` distribution.
* otherwise refactors the `Empirical` distribution to adopt the new extender API
> [ENH] improved `Empirical` distribution - scalar mode, new API compatibility

- skpro/distributions/base/_base.py
This PR increases the default resolution of `plot` figures from 100 to 1000 points.
This is to prevent step functions from looking piecweise linear and not like step functions.
> [ENH] increase distribution default `plot` resolution

- skpro/distributions/base/_base.py
- skpro/distributions/tests/test_proba_basic.py
Adds `head` and `tail` methods for distribution objects, with same syntax and behaviour as for `pd.DataFrame`. Includes tests.
> [ENH] `head` and `tail` for distribution objects

- skpro/distributions/empirical.py
This PR adds full support of hierarchical `MultiIndex` `index` in `Empirical` distribution, and tests, via `get_test_params`.
> [ENH] full support of hierarchical `MultiIndex` `index` in `Empirical` distirbution, tests

- skpro/regression/ensemble/_ngboost.py
#301 , #215 
This PR ensures `NGBoostRegressor` inherits the common conversions from the `ngboost` distribution to `skpro` distribution from the `NGBoostAdapter` class. This adapter is common to both the `NGBoostSurvival` and `NGBoostRegressor`.
> [MNT] refactor `NGBoostRegressor` to inherit `NGBoostAdapter`

- skpro/metrics/base.py
- skpro/metrics/survival/_c_harrell.py
- skpro/metrics/survival/tests/test_c_harrell.py
This fixes an unreported bug in which survival metrics break if `C_true=None` is passed as part of `kwargs`, as opposed to not being passed.
This is due to the boilerplate layer passing passing an empty `pd.DataFrame` to the inner `_evaluate` (due to coercion if the argument is present), which may lead to breakage in metrics that do not ignore it, e.g., `ConcordanceHarrell`.
The fix is ensuring that the boilerplate layer passes on `None` in this case.
Also fixes some minor issues with `ConcordanceHarrell` masked by this problem:
* `evaluate_by_index` could return `nan` if a sample was not comparable. This is replaced by `tie_score`
* the `test_charell_logic` test made incorrect assumption about resulting concordances, this has been fixed.
> [BUG] fix survival metrics if `C_true=None` is passed

- skpro/survival/compose/_reduce_cond_unc.py
This PR ensures coercion to float, of the `C` argument, in the `ConditionUncensored` reducer.
This makes the estimator safer to non-compliant inputs.
> [ENH] in `ConditionUncensored` reducer, ensure coercion to float of `C`

- pyproject.toml
PR https://github.com/sktime/skpro/pull/327 shows that the `findiff` soft dependency is not necessary - with this, I hence remove it.
We should either merge #327, or leave the QPDs with a soft dependency that users then have to install independently.
> [MNT] remove `findiff` soft dependency

- skpro/distributions/base/_base.py
The approximation fallback for Monte Carlo estimation of a distribution's variance, in `BaseDistribution._var`, was missing a factor two by accident.
This PR adds that missing factor.
> [BUG] `BaseDistribution._var`: fix missing factor 2 in Monte Carlo variance default method

- docs/source/api_reference/distributions.rst
- skpro/distributions/__init__.py
- skpro/distributions/exponential.py
This interfaces the `Exponential` distribution using the `_ScipyAdapter`.
No
Yes
(https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).
> [ENH] `Exponential` distribution

- skpro/distributions/base/_base.py
This PR adds improved defaults for `BaseDistribution` `_mean`, `_var`, and `_energy_x`.
The current defaults are Monte Carlo estimates for these quantities, using `sample`.
A faster and more accurate estimtate is obtained from integrating the `ppf`, which can be done only if it is available.
An example is the identity $\mathbb{E}[X] = \int_{0}^1 F_X^{-1}(x) \mbox{ } dx$, which is true for any real random variable `X`. Similar identities can be derived for variance and energy cross-term, which are both expectations in a single copy of `X`.
one could also do sth similar for gridding or triangulating the self-term, but it is not obvious whether that is better than sthe uniform sampling strategy, so it is not included in this PR.
> [ENH] improved defaults for `BaseDistribution` `_mean`, `_var`, and `_energy_x`

- pyproject.toml
- skpro/distributions/qpd.py
- skpro/distributions/tests/test_qpd.py
This PR reworks the family of QPD family of distributions for efficiency and to allow removal of the newly introduced dependency `findiff` in #232.
The dependency `findiff` was introduced for approximation of `pdf`, but in fact it is unnecessary as the `pdf` can be analytically derived by applying the chain rule. True, it has to be applied three or four times, but it's still the chain rule... efficiency and accuracy gains are significant, and it helps us avoid computing numerical derivatives for all entries in a large matrix, together with the now unnecessary `findiff` dependency.
Makes the following changes:
* refactoring of the three QPD distributions tp use `skpro` machinery:
* use of the `skpro` native parameter broadcasting system instead of ad-hoc broadcasting
* use of the `skpro` …
> [ENH] native implementation of Johnson QPD family, explicit pdf

- skpro/regression/cyclic_boosting.py
Recent PR brought the QPDistributions in line with unified `skpro` row/column conventions, where 1D vectors are interpreted as row vectors.
This clashes with assumed coercion about the now-changed QPDistributions (it assumed column vectors) inside `CyclicBoosting`, which needed to be fixed.
> [ENH] fix distribution row/column convention in `CyclicBoosting`

- pyproject.toml
- skpro/regression/cyclic_boosting.py
Deprecation messages for `CyclicBoosting` for deprecations and changes in 2.4.0.
Alternative to #320.
* restores sequence of parameters to sequence in version 2.2.2, to avoid breakage in the 2.3.0 release
* adds deprecation message for `bound` parameter
* renames new `version` parameter to `dist_type` - the name is a bit misleading, as it will probably imply "version" in the semantic versioning sense to an ordinary user. Does not require deprecation, because added since 2.2.2.
Also makes improvements to the docstring of the `CyclicBoosting` estimator.
Difference to #320: does not carry out deprecations for distributions, under a working assumption that #327 will be merged.
> [MNT] deprecation handling for `CyclicBoosting`

- .all-contributorsrc
- docs/introduction.rst
- docs/source/changelog.rst
- docs/source/conf.py
- docs/source/contribute/code_of_conduct.rst
- docs/source/developer_guide/dependencies.rst
- docs/source/developer_guide/deprecation.rst
- docs/source/developer_guide/reviewer_guide.rst
- docs/source/installation.rst
- examples/01_skpro_intro.ipynb
- examples/02_skpro_survival.ipynb
- examples/03_skpro_distributions.ipynb
- extension_templates/regression.py
- extension_templates/survival.py
- skpro/datatypes/_convert.py
- skpro/datatypes/_convert_utils/_convert.py
- skpro/datatypes/tests/test_convert_to.py
- skpro/distributions/base/_base.py
- skpro/distributions/delta.py
- skpro/distributions/empirical.py
- skpro/metrics/base.py
- skpro/regression/cyclic_boosting.py
- skpro/regression/density.py
- skpro/regression/tests/test_cyclic_boosting.py
- skpro/survival/ensemble/_survforest_sksurv.py
- skpro/tests/scenarios/scenarios_getter.py
- skpro/utils/_maint/tests/test_show_versions.py
- skpro/utils/numpy.py
Found few misspellings all over the project.
@fkiraly https://github.com/crate-ci/typos
> [DOC] Fix typos throughout the codebase

- build_tools/changelog.py
This PR isolates imports in the `changelog.py` build util, as these are specific to the build tool and show up in dependency analyses - but they are not part of the package proper.
> [MNT] isolate imports in `changelog.py` build util

- skpro/tests/tests/test_test_utils.py
The `test_run_test_for_class` test logic was erroneous in case the class with dependency was changed.
This is due to an accidental variable overwrite, `run_no_dep` being overwritten with the value from the test class with dependencies.
Spotted through failure in https://github.com/sktime/skpro/pull/343, which changed the "class with dependencies" example.
> [BUG] fix `test_run_test_for_class` test logic

- build_tools/changelog.py
- skpro/regression/bootstrap.py
`BootstrapRegressor` has a parameter `random_state` but - by error - it did not do anything.
The `random_state` is now correctly connected to the bootstrap sampling.
> [BUG] fix `random_state` handling in `BootstrapRegressor`

- skpro/utils/git_diff.py
If an `lru_cache`-d function returns a mutable object, and that object is later muted, the cached function wlil continue returning the muted - incorrect - return.
This PR fixes the one instance in the code base where this issue could arise.
Mirror of https://github.com/sktime/sktime/pull/6451
> [ENH] make `get_packages_with_changed_specs` safe to mutation of return

- docs/source/api_reference/regression.rst
- examples/01_skpro_intro.ipynb
- skpro/regression/enbpi.py
- skpro/tests/tests/test_test_utils.py
This implements an EnbPI tabular regressor wrapper, see https://github.com/sktime/sktime/issues/6446.
This is a de-novo implementation based on the paper [Conformal Prediction Interval for Dynamic Time-series](http://proceedings.mlr.press/v139/xu21h.html) (Xu et al. 2021a)
FYI @hamrel-cxu, a review would be appreciated. Let me know if you would like to take on maintenance and become owner of this algorithm.
> [ENH] EnbPI regressor for conformal prediction intervals

- skpro/distributions/empirical.py
- skpro/distributions/tests/test_empirical.py
Fixes the index of `spl` in the resulting distribution when subsetting `Empirical` distributions via `iat`.
At current `main`, the wrong index level was dropped. The resulting index should be the index with the lowest index, not the index with the highest index.
> [BUG] fix `spl` index when subsetting `Empirical` distribution via `iat`

- skpro/distributions/base/_base.py
This improves the default function selected by `BaseDistribution.plot`, depending on the measure type of the distribution.
Continuous distributions will still plot `pdf`, while discrete distributions and mixed distributions will plot `cdf`.
This change is deprecation safe, as plotting outputs are not reused (only shown), and `pdf` plots of continuous distributions result in uninformative constant zero plots.
> [ENH] improved default function to plot via `BaseDistribution.plot`, depending on distribution type

- docs/source/api_reference/distributions.rst
- skpro/distributions/__init__.py
- skpro/distributions/compose/__init__.py
- skpro/distributions/compose/_iid.py
This introduces an iid compositor for array distributions.
This allows to define copies of identical distributions through composition, which is useful especially if the sampled distribution has a complex specification that is not easy to use for this end, e.g., `Empirical` which currently would require unnecessarily repeating samplies.
> [ENH] iid array distribution

- docs/source/api_reference/distributions.rst
- skpro/distributions/__init__.py
- skpro/distributions/alpha.py
Implements Alpha Distribution. Towards https://github.com/sktime/skpro/issues/22
No
No
> [ENH] Alpha distribution

- skpro/datatypes/_check.py
- skpro/model_selection/_tuning.py
Carries out deprecations and change actions scheduled for 2.3.0. Note: these were omitted by error in 2.3.0, and are now carried out in 2.3.1.
* change default of `check_is_mtype` parameter `msg_return_dict` to `dict`
* removal of `n_jobs` and `pre_dispatch` parameters was prevented through missing future parameter in grid search classes. Bumped to 2.5.0.
> [MNT] 2.3.0 deprecations and change actions

- docs/source/api_reference/survival.rst
Fixes a typo that caused an empty GAM survival model section in the API reference.
> [DOC] fix typo in survival models API reference

- docs/source/api_reference/distributions.rst
- skpro/distributions/__init__.py
- skpro/distributions/loglaplace.py
#22 
Implements Log Laplace Distribution
> [ENH] Log Laplace Distribution

- docs/source/api_reference/distributions.rst
- skpro/distributions/__init__.py
- skpro/distributions/halflogistic.py
#22 
Implements Half Logistic distribution
No
> [ENH] Half Logistic Distribution

- skpro/distributions/tests/test_all_distrs.py
fixes #380 
`object_instance` is the distribution before shuffling.
`d` is the one after shuffling so it needs to be used instead 
`res=getattr(object_instance,method)(p)` to be replaced with `res = getattr(d, method)(p)` as this will account for the object_instance after shifting the distribution. This will ensure the outputs are checked with the shifted distribution's instance.
> [BUG] fix `test_methods_p` logic when `shuffle` is `True`

- skpro/regression/linear/_sklearn.py
Fixes #385 . 
@fkiraly I couldn't specify `inf` as a `max_iter` since the allowed values range between [1, inf) with inf as an open interval. Instead I chose 300 because thats what the docstring said previously. Let me know if you want something else set as the default value.
> [BUG] - bugfix when `None` was specified for `max_iter` parameter in sklearn regressors

- docs/source/api_reference/metrics.rst
- skpro/metrics/__init__.py
- skpro/metrics/_classes.py
- skpro/metrics/tests/test_probabilistic_metrics.py
This PR adds interval width and area under calibration curve metrics from `sktime`. Until refactor, the metrics modules should be kept in sync.
> [ENH] interval width and area under calibration curve metrics

- skpro/distributions/tests/test_all_distrs.py
- skpro/regression/linear/_glm.py
- skpro/regression/tests/test_glm.py
fixes #383 and closes #230
This creates an adapter converting the statsmodels GLM families to skpro equivalent giving `GLM`s a broader capability of distributions and link functions.
No
Yes
dependency isolation, see the [estimator dependencies …
> [ENH] `GLM` with multiple `distributions` and `link` function support

- docs/source/api_reference/distributions.rst
- skpro/distributions/__init__.py
- skpro/distributions/pareto.py
Addresses #22 for the Pareto distribution
Implements some methods for the Pareto distribution
No
Current state of code, and how to add energy
No
No
- [Yes] I've added myself to the [list of contributors](https://github.com/sktime/skpro/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
See here for [full badge …
> [ENH] Pareto distribution

- skpro/distributions/alpha.py
- skpro/distributions/beta.py
- skpro/distributions/exponential.py
- skpro/distributions/fisk.py
- skpro/distributions/gamma.py
- skpro/distributions/halfcauchy.py
- skpro/distributions/halflogistic.py
- skpro/distributions/halfnormal.py
- skpro/distributions/loglaplace.py
- skpro/distributions/poisson.py
This PR adds a `scipy` reference in docstrings of interfaced distributions from `scipy`.
> [DOC] add `scipy` reference to interfaced distributions

- docs/source/api_reference/distributions.rst
- skpro/distributions/base/__init__.py
- skpro/distributions/base/_base_array.py
- skpro/distributions/histogram.py
This PR makes `BaesArrayDistribution` private.
This is due to the imminent release - if it is private, we can change interfaces later without having to go through the deprecation process. This includes changes such as merging into the base class.
FYI @ShreeshaM07.
> [MNT] make `BaseArrayDistribution` private

- skpro/distributions/base/_base.py
This PR fixes an unreported bug in the `BaseDistribution`, it ensures that `index` and `columns` are taken into account in boilerplate broadcasting if the `bc_params` tag is set.
> [BUG] ensure `index` and `columns` are taken into account in broadcasting if `bc_params` are set

- pyproject.toml
This PR bumps the bound for `numpy` to `<2.1`.
> [MNT] increase `numpy` bound to `numpy < 2.1`, `numpy 2` compatibility

- skpro/regression/cyclic_boosting.py
- skpro/regression/linear/_glm.py
Carries out deprecations and change actions scheduled for 2.4.0.
* in `CyclicBoosting`, final removal of `bounds` parameter
* bump an action erroneously scheduled for 2.4.0 to 2.5.0 (in GLM)
> [MNT] 2.4.0 deprecations and change actions

- skpro/distributions/base/_base_array.py
fixes #412 
The error is due to the deprecation of the np.broadcast_arrays. https://numpy.org/doc/stable/reference/generated/numpy.broadcast_arrays.html
So the bc is actually a tuple with broadcasted arrays whose values are getting reassigned.
dependency isolation, see the …
> [BUG] Histogram Distribution: address `np.broadcast_arrays` deprecation of writable return in `numpy 2.0.0`

- skpro/tests/test_switch.py
- skpro/utils/git_diff.py
This PR syncs differential testing utilities with `sktime` anticipating a joint refactor to `skbase`.
Counterpart of https://github.com/sktime/sktime/pull/6840
Modules affected:
* `skpro.tests.test_switch`
* `skpro.utils.git_diff`
> [MNT] sync differential testing utilities with `sktime`

- docs/source/api_reference/distributions.rst
- skpro/distributions/__init__.py
- skpro/distributions/truncated_normal.py
Interfaces truncated normal distribution from scipy.
No
Yes
> [ENH] Truncated Normal distribution

- skpro/datatypes/_check.py
- skpro/datatypes/_convert.py
As per requested by @fkiraly, we are updating the files `_check.py` and `_convert.py` to match functionality with the `sktime` library. Note that `_common.py` is exactly the same for both libraries, so no changes were needed. 
This pr also should allow list of strings to be accepted as valid `X_inner_mtype` and `y_inner_mtype`.
@fkiraly Could you please do a review to ensure that the code is correct?
Thanks!
> [ENH] Syncing datatypes module `_check.py` and `_convert.py` with `sktime`

- skpro/distributions/pareto.py
This fixes `numpy 2` incompatibility of the `Pareto` distribution - removd `np.infty` replaced by `np.inf`.
> [MNT] fix `numpy 2` incompatibility of `Pareto` distribution

- skpro/distributions/qpd.py
- skpro/model_selection/_tuning.py
- skpro/regression/linear/_glm.py
Carries out deprecations and change actions scheduled for 2.5.0.
* in QPD distributions, remove `version` and `dist_shape` parameters
* in QPD distributions, remove `lower` and `upper` parameters where not used
* in `GLMRegressor`, reorder parameters as announced in warning
* in probabilistic regression tuners, remove `n_jobs` and `pre_dispatch` in favour of `backend` and `backend_params` parameters
> [MNT] 2.5.0 deprecations and change actions

- skpro/regression/cyclic_boosting.py
The deprecations to `QPD_Johnson` from #443 were not consistent with how it is called from `CyclicBoosting` - this has been updated to match.
> [MNT] ensure `CyclicBoosting` is consistent with deprecations in `QPD_Johnson`

- skpro/datatypes/_adapter/polars.py
- skpro/datatypes/_table/_convert.py
- skpro/datatypes/_table/_examples.py
- skpro/datatypes/tests/test_polars.py
adds index support as part of #440 and is used to sync up polars conversion utilities between skpro and sktime.
Correponding sktime pr for polars conversion utilities is https://github.com/sktime/sktime/pull/6455/.
In this pr:
If a pandas Dataframe is a `from_type` and polars frame is a `to_type` then during the conversion, we will save the index (assumed never to be in multi-index format) and insert it as an individual column with column name `__index__`. Then the resulting pandas dataframe will be converted to a polars dataframe.
In the inverse function, if we are converting from polars dataframe to pandas dataframe, if the column `__index__` exists in the pandas dataframe post-conversion, then we will map that column to the index before returning the pandas Dataframe
After this is …
> [ENH] Polars adapter enhancements

- skpro/regression/dummy.py
This fixes an unreported bug for `DummyProbaRegressor(strategy="normal")`, where the variance was used instead of the standard deviation, leading to too large variance estimates.
> [BUG] fix variance bug in `DummyProbaRegressor`

- skpro/datatypes/_base/__init__.py
- skpro/datatypes/_base/_base.py
- skpro/datatypes/_examples.py
- skpro/datatypes/_proba/__init__.py
- skpro/datatypes/_proba/_examples.py
- skpro/datatypes/_table/__init__.py
- skpro/datatypes/_table/_examples.py
This PR refactors the data type specifications and converters to classes.
Related: https://github.com/sktime/sktime/issues/3512, related to https://github.com/sktime/sktime/issues/2957.
Contains:
* a base class for datatype examples, `BaseExample`, to replace the more ad-hoc dictionary design
* a complete refactor of the `Table` and `Proba` mtype submodules to this interface
* a full refactor of the public framework module with `get_example` logic, in `datatypes`, to allow extensibility with this design
Partial mirror in `skpro` of https://github.com/sktime/sktime/pull/6033
> [ENH] refactor `datatypes` mtypes - example fixtures

- skpro/datatypes/_examples.py
- skpro/datatypes/_proba/_examples.py
- skpro/datatypes/_table/_examples.py
This syncs the `datatypes` examples module with `sktime`:
* update the docstrings to the class based architecture
* ensure examples are deepcopied before returned
> [ENH] `datatypes` examples - docstrings, deepcopy

- skpro/regression/base/_base.py
This syncs the `_get_columns` utility used for generating expected columns of `predict_interval` and `predict_proba` with `sktime`.
> [ENH] sync proba predict utils with `sktime`

- docs/source/api_reference/regression.rst
- skpro/registry/_tags.py
- skpro/regression/base/_base.py
- skpro/regression/base/_delegate.py
- skpro/regression/compose/_pipeline.py
- skpro/regression/online/__init__.py
- skpro/regression/online/_dont_refit.py
- skpro/regression/online/_refit.py
- skpro/regression/tests/test_all_regressors.py
- skpro/survival/base.py
Adds framework support for online update capability for probabilistic regressors, and a simple composite strategy that refits on all data, for testing the framework. Closes https://github.com/sktime/skpro/issues/463
Contains:
* extension of the regressor and survival base class with a potential `update` / `_update` method for batch updates
* addition of a tag `capability:online` for respective estimators
* addition of a composite `OnlineRefit` that adds the `capability:online` tag and refits the regressor upon all data seen so far. This is a separate estimator to avoid that all estimators remember (and clutter `self`) with the data
* a similar composite `OnlineDontRefit` that turns off online capability
* a specific test case for online updates, in `TestAllRegressors`
> [ENH] online update capability for probabilistic regressors

- docs/source/api_reference/regression.rst
- skpro/regression/online/__init__.py
- skpro/regression/online/_refit_every.py
Adds an online fitting strategy that calls `update` of a wrapped regressor only after N new data points have been seen.
> [ENH] online refitting strategy after N data points

- skpro/utils/git_diff.py
The differential testing utilities would result in exceptions in cases where `pyproject.toml` was changed with non-package related changes.
This PR modifies the utilities to fix this, bringing them in sync with sktime.
> [MNT] differential testing - handle non-package changes in `pyproject.toml`

- skpro/datatypes/_table/_check.py
This PR removes some unnecessary `__init__` methods in `datatypes` module - the `__init__` function in question just call `super` and pass on all parameters, so they can be removed without impacting anything.
> [ENH] minor refactor - remove unnecessary `__init__` methods in `datatypes` module

- .github/workflows/test.yml
- .github/workflows/wheels.yml
- pyproject.toml
Extends the bounds in `pyproject.toml` to add experimental support for python 3.13, and adds testing on 3.13 to the test matrix.
Full 3.13 support to be added with 2.7.0.
> [MNT] python 3.13 support, add 3.13 to test matrix

- skpro/registry/_tags.py
- skpro/regression/base/_base.py
- skpro/regression/compose/_pipeline.py
- skpro/regression/online/_dont_refit.py
- skpro/regression/online/_refit.py
- skpro/regression/online/_refit_every.py
- skpro/survival/base.py
This PR renames the `capability:online` tag to `capability:update`.
This is more in line with tags that describe whether methods are present, most being called `capability:methodname`.
No deprecation is necessary, as the online update API has not been released yet.
> [ENH] rename `capability:online` tag to `capability:update`

- .github/workflows/test.yml
This PR fixes the failing `code-quality` CI step, by replacing the deprecated `pre-commit` action.
> [MNT] fix failing `code-quality` CI step

- .all-contributorsrc
- skpro/utils/_maint/_show_versions.py
- skpro/utils/_maint/tests/test_show_versions.py
- skpro/utils/validation/_dependencies.py
Potentially fixes #358 (failing Python tests)
Addresses issue #489
Synchronized dependency checking utilities in utils with the one from `sktime`
The current version is a fork of a much earlier version of `sktime` and is problematic as it must import packages in order to check presence of dependencies. This is causing the failures in the test collection phase in #358, or more generally, in a case where the imported package is faulty, with import causing exceptions.
No
Compatibility of the content with  the wider `skpro` ecosystem
Yes, I copied the corresponding dependency test `test_show_versions` from `sktime`
No
> [ENH] Synchronize dependency checker with `sktime` counterpart

- skpro/tests/_config.py
- skpro/tests/test_all_estimators.py
This PR sets up an exclude list for estimators in `skpro`.
Similar to `sktime`, excluded tests or estimators can now be specified in `skpro.tests._config`.
Also adds a skip for https://github.com/sktime/skpro/issues/497.
> [ENH] set up exclude list for estimators

- docs/source/api_reference/distributions.rst
- skpro/distributions/__init__.py
- skpro/distributions/erlang.py
Implementing a distribution towards #22 
Implements Erlang Distribution
No
Sorry for the issue on Previous PR #517 .
> [ENH] Erlang Distribution

- skpro/distributions/t.py
Fixes some mathematical errors in the docstring of the `TDistribution`:
* the `mean` is not a mean as it may not exist. Replaced with median in the explanation.
* the `sd` is in general not the standard deviation, which may also not exist. Corrected the explanation.
> [DOC] improved docstring for the `TDistribution`

- .github/workflows/wheels.yml
Moves the release to trusted publishers.
All secrets have been removed from the repo.
> [MNT] move release to trusted publishers

- skpro/utils/_maint/tests/test_show_versions.py
Removes the deprecated `pkg_import_alias` from private soft dependency checker tests
> [MNT] remove deprecated `pkg_import_alias` from private soft dependency checker tests

- skpro/regression/base/_base.py
- skpro/regression/mapie.py
This PR fixes two unreported bugs:
* the `MapieRegressor` dependency check was always failing due to the capitalization of `MAPIE` on pypi - not `mapie`. This led to the estimator not being useable since the upgrade to strict PEP 440 (which included capitalization sensitivity) of the `python_dependencies` tag.
* the `BaseProbaRegressor._predict_proba` sensible default would not work properly if the expected return of `predict` was not a `pd.DataFrame`. This has been remedied by using the idiomatic method `_get_columns` to determine the column names.
> [BUG] fix `MapieRegressor` dependency check, and `BaseProbaRegressor._predict_proba` default

- skpro/regression/ensemble/_ngboost.py
- skpro/survival/ensemble/_ngboost_surv.py
This PR fixes `NgboostRegressor` not working with custom `sklearn` estimator.
In this case, the estimator clone was not properly initialized internally.
This was not detected since none of the seven (!) test cases contained a non-default for the estimator.
> [BUG] fix `NgboostRegressor` not working with custom `sklearn` estimator

- skpro/distributions/erlang.py
- skpro/distributions/meanscale.py
- skpro/regression/delta.py
- skpro/tests/test_all_estimators.py
- skpro/tests/test_doctest.py
- skpro/utils/_doctest.py
This PR fixes the doctest runs via the testing framework.
Previously, failures were only causing printouts but no exceptions, as intended.
> [BUG] fix doctest runs in testing framework

- skpro/regression/multiquantile.py
This Pr sets sensible defaults for `MultiQuantileRegressor` components - namely, `GradientBoostingRegressor`.
A test case for all-defaults is added.
FYI @Ram0nB.
> [ENH] `MultiQuantileRegressor` sensible defaults

- skpro/metrics/_classes.py
- skpro/metrics/base.py
syncs the probabilistic metrics with `sktime`:
* complete docstrings
* allowing `alpha` and `coverage` to be passed to the metric constructors
> [ENH] sync probabilistic metrics with `sktime`

- .github/workflows/wheels.yml
- docs/source/changelog.rst
This PR updates the release wheel build runner to `ubuntu-latest`, from a removed fixed ubuntu version.
> [MNT] update release wheel build runner to `ubuntu-latest`

- .github/workflows/wheels.yml
Release permissions where missing in the `wheels` workflow, these are added here
> [MNT] add release permissions in `wheels` workflow

- skpro/utils/estimator_checks.py
This PR ensures that `check_estimator` also prints out the partial log in the failure case.
Mirrors the `sktime` status quo; also adds a check for the inner `verbose` parameter in `skbase` `QuickTester.run_tests` to ensure downwards compatibility.
> [ENH] verbose printout for `check_estimator` in `raise_exceptions` case

- docs/source/changelog.rst
- skpro/regression/mapie.py
The `MAPIE` package have restructured their regression algorithms in 1.0, see https://github.com/sktime/skpro/issues/563.
The current `MapieRegressor` gets the `MAPIE<1.0` dependency bound, new estimators should be added according to issue https://github.com/sktime/skpro/issues/563.
> [ENH] `MAPIE<1.0` bound for legacy `MapieRegressor`

- skpro/survival/coxph/_coxph_lifelines.py
The second test parameter setting for `CoxPHlifelines` has sporadic convergence issues on the CI test data.
This PR improves the parameter settings to be more stable.
> [ENH] improving stability of test parameter settings for `CoxPHlifelines`

- skpro/distributions/poisson.py
The "approximate vs exact" tag for the `Poisson` distribution were not set correctly - `Poisson` has an exact `ppf` interfaced from `scipy`.
Also fixes a problem with the 2nd test example which had a (non-permissible) mean zero for the Poisson.
> [BUG] correctly set tags for `Poisson` distribution

- skpro/distributions/hurdle.py
- skpro/distributions/truncated.py
Fixes #566.
Moves the epsilon offset logic for the Hurdle distribution to Truncated instead.
No.
No.
The tests pass locally, so I'm hoping this solves the issues.
dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependenci …
> [ENH] Moves epsilo offset logic to `TruncatedDistribution` from `Hurdle`

- README.md
The license badge in README was linking to `sktime` instead of to the `skpro` license - this PR fixes that.
> [DOC] fix badge link to license in README

- skpro/regression/binned/_sklearn_bin_regressor.py
- skpro/regression/tests/test_all_regressors.py
Fixes an unreported bug in `HistBinnedRegressor.predict` which would return majority classes rather than the mean of the histogram distribution.
A corresponding test is also added to `TestAllRegressors` to ensure that all `predict` returns are float dtyped.
> [BUG] fix `HistBinnedRegressor.predict` return type

- .all-contributorsrc
- skpro/distributions/base/_base.py
Fixes #591
Very simply, it replaces a pandas `.apply` (which under the hood is just a loop) with a pandas/numpy native ufunc. This mean that is operation is now fully vectorised.
No
Edge cases such as how the reviewer expects values such as `np.inf` and `np.NaN` to be handled.
No tests added. All previous tests passed.
Reduction in total run time for line `_base.py:1207` was from 16.56 seconds to 0.11 seconds (150x speed-up).
Modified example from `examples/01_skpro_intro.ipynb`:
```python
import pandas as pd
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold
from skpro.benchmarking.evaluate import evaluate
from skpro.metrics import CRPS
from skpro.regression.residual import ResidualDouble
n_copies = 10
X, …
```
> [ENH] replace apply linalg norm with native pandas ufuncs

- docs/source/api_reference/distributions.rst
- skpro/distributions/__init__.py
- skpro/distributions/qpd.py
This PR ensures all distributions are exported in `skpro.distributions`, and makes minor fixes to API reference.
* adds all distributions to `skpro.distributions` module export
* fixes missing distributions in API reference
* fixes to description of distributions
> [ENH] export all distributions in `skpro.distributions`, minor fixes to API reference

- skpro/regression/xgboostlss.py
XGBoostLSS uses pytorch backend with "concentration" nomenclature instead of skpro alpha and beta.
No reference as it is a very simple PR.
This adds the Beta Distribution to XGBoostLSS. It is a simple conversion from the [pytorch Beta](https://docs.pytorch.org/docs/stable/distributions.html#beta) to skpro Beta. It is the simple mapping of `concentration1 -> alpha` and `concentration0 -> beta`.
No.
Only one line of code and one line of docs changed.
Yes. Added Beta to the XGBoostLSS `get_test_params`.
No.
How to: add yourself to the [all-contributors file](https://github.com/sktime/skpro/blob/main/.all-contributorsrc) in the `skpro` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or …
> [ENH] Add Beta Distribution to XGBoostLSS

- skpro/distributions/base/_base.py
- skpro/distributions/tests/test_base_default_methods.py
This PR fixes an unreported but with the approximate `cdf` used whenever the distribution does implement only a `sample` method.
The current state had an error of sign, where the indicator function was flipped the wrong way round, so the function estimated was 1 - cdf, and not the cdf.
This is now fixed; a test is added to prevent regression.
> [BUG] fix approximate `cdf` for distributions without implementation

- skpro/distributions/trafo/_transformed.py
- skpro/regression/compose/_ttr.py
This PR adds `cdf` support to `TransformedTargetRegressor`, via changes in `TransformedDistribution`:
* `TransformedDistribution` now accepts `inverse_transform`, which can be used for an exact `cdf`
* `TransformedTargetRegressor` passes the fitted `self.transformer_transform` to the `inverse_transform` of `TransformedDistribution`
Together with https://github.com/sktime/skpro/pull/610, it means that `TransformedTargetRegressor` can now produce distributions with reasonably reliable `cdf` and `pdf`.
Goes partially towards #601.
> &joshdunnlime [ENH] `TransformedDistribution` and `TransformedTargetRegressor` `cdf` support

- skpro/distributions/trafo/_transformed.py
- skpro/regression/compose/_ttr.py
This PR fixes a few of bugs with `TransformedDistribution` subsetting:
* indices were not properly coerced for all `iloc` calls
* scalar distibutions were not correctly handled
> [BUG] fixes to `TransformedDistribution` subsetting
