- skpro/distributions/__init__.py
- skpro/distributions/laplace.py
Adds Laplace distribution to available distributions.
> [ENH] Laplace distribution

- skpro/distributions/__init__.py
- skpro/distributions/empirical.py
- skpro/distributions/laplace.py
Adds empirical distribution.
Towards https://github.com/sktime/skpro/issues/22.
Mirror of https://github.com/sktime/sktime/pull/5094
> [ENH] empirical distribution

- pyproject.toml
- skpro/tests/test_baselines.py
- skpro/tests/test_parametric.py
- skpro/tests/utils.py
This PR updates the `sklearn` bound to `<1.4.0`.
> [MNT] update `sklearn` bound to `<1.4.0`

- skpro/registry/tests/__init__.py
- skpro/registry/tests/test_tags.py
Adds a test which checks the validity of the tag registry.
> [ENH] add specification test for the tag registry

- .all-contributorsrc
This PR ads an `.all-contributorsrc` file with current contributors.
FYI @frthjf, @iwitaly, @Alex-JG3, @yarnabrina.
> [ENH] adds `.all-contributorsrc` file with current contributors

- .pre-commit-config.yaml
Upgrades `pre-commit` versions and steps to the same as `sktime`.
> [MNT] `pre-commit` hook upgrade

- skpro/metrics/__init__.py
- skpro/metrics/_classes.py
This adds the linearized log-loss as a probabilistic metric.
> [ENH] linearized log-loss

- pyproject.toml
This PR releases the sphinx version bounds, and should resolve the sphinx build issues on readthedocs.
> [MNT] update sphinx versions

- README.md
> [DOC] shorter README.md preamble

- docs/source/about/history.rst
Forgot to give credit to @yarnabrina in the skpro history - rectified.
> [DOC] Add yarnabrina to skpro history

- docs/source/index.rst
Corrects the content on the index page - copy/paste accident while moving directories.
> [DOC] correct index page

- .github/workflows/wheels.yml
corrects the wheelname logic in the release workflow (`wheels`)
> [MNT] correct wheelname in release workflow

- examples/01_skpro_intro.ipynb
Some small improvements to notebook 1:
* multiple `alpha`, `coverage`
* output type explanation text
> [ENH] improvements to notebook 1

- .github/dependabot.yml
This PR activates `dependabot` for version updates and maintenance.
> [MNT] activate `dependabot` for version updates and maintenance

- docs/source/_static/switcher.json
- docs/source/changelog.rst
- pyproject.toml
- skpro/__init__.py
Release PR for 2.1.0
* changelog
* version bump
> Release 2.1.0

- .github/workflows/wheels.yml
Code for getting wheel name for windows wheel test is incorrect, fixed.
Also deactivate fail-tast flag for better diagnostics.
> [MNT] fix wheels test for release

- .github/workflows/test.yml
Changest test OS versions to latest from specific historic versions.
> [MNT] change test OS versions to latest

- README.md
- docs/source/_static/switcher.json
- docs/source/changelog.rst
- pyproject.toml
- skpro/__init__.py
Release PR for 2.1.1
* changelog
* version bump
> [MNT] Release 2.1.1

- README.md
- docs/source/_static/switcher.json
- docs/source/changelog.rst
- pyproject.toml
- skpro/__init__.py
Release PR for 2.1.2
* changelog
* version bump
* added download tracker on landing page
> Release 2.1.2

- skpro/regression/gp/_sklearn.py
- skpro/regression/linear/_sklearn.py
This fixes various bugs in the delegated `sklearn` probabilistic regressors:
* missing parameter write to `self`
* an erroneously passed parameter in the test cases
> [BUG] fix various bugs in delegated `sklearn` probabilistic regressors

- README.md
- docs/source/_static/switcher.json
- docs/source/changelog.rst
- pyproject.toml
- skpro/__init__.py
- skpro/datatypes/_table/_check.py
Release PR for 2.1.3
* changelog
* version bump
> Release 2.1.3

- docs/source/api_reference.rst
- docs/source/api_reference/metrics.rst
Adds an API reference for performace metrics.
> [DOC] API reference for performance metrics

- README.md
- docs/source/_static/switcher.json
- docs/source/changelog.rst
- pyproject.toml
- skpro/__init__.py
Release PR for 2.2.0
* changelog
* version bump
> Release 2.2.0

- skpro/distributions/t.py
Fixes https://github.com/sktime/skpro/issues/209, direct mirror of same `sktime` patch.
Credit goes entirely to @ivarzap.
> ivarzap [BUG] fix missing location/scale in `TDistribution`

- README.md
- docs/source/_static/switcher.json
- docs/source/changelog.rst
- pyproject.toml
- skpro/__init__.py
Release PR for 2.2.1
* changelog
* version bump
> Release 2.2.1

- docs/source/conf.py
Reverts sktime/skpro#125
Experimental, upon suggestion of @duydl in https://github.com/sktime/skpro/issues/224
> Revert "[MNT] point readthedocs `json` switcher variable to GitHub"

- docs/source/api_reference/distributions.rst
- skpro/distributions/__init__.py
- skpro/distributions/poisson.py
This PR adds a Poisson distribution.
The implementation is rudimentary, aiming at the minimum methods to be implemented.
The intention is to use this example to develop framework capability for discrete and mixed distributions.
> [ENH] Poisson distribution

- skpro/metrics/_classes.py
- skpro/metrics/tests/test_distr_metrics.py
This PR adds test parameters to the probabilistic metrics.
Also improves formatting of the docstrings.
> [ENH] add test parameters to probabilistic metrics, docs improvement

- .all-contributorsrc
- skpro/survival/compose/_reduce_cond_unc.py
@julian-fong forgot to add their badges to `all-contributorsrc` for #222, this PR adds them.
Also fixes an unrelated typo.
> [DOC] add julian-fong to `all-contributorsrc`

- docs/source/api_reference/distributions.rst
- skpro/distributions/__init__.py
- skpro/distributions/weibull.py
https://github.com/sktime/skpro/issues/22
Weibull probability distribution
no
- Yes, I try to install this library locally using `pip install --editable .[dev,test]` and create a simple driver program to use this new distribution
* I use the formula from Wikipedia, which can be accessed [here](https://en.wikipedia.org/wiki/Weibull_distribution)
See here for [full …
> [ENH] Weibull distribution

- skpro/distributions/lognormal.py
Fixes small things relate dto the `LogNormal` distribution:
* fixed parameter names in docstring
* clarification of parameterization
* `icdf` was incorrect, fixed that
> [BUG] fixes to lognormal distribution

- extension_templates/regression.py
- extension_templates/survival.py
Fixes some issues with current extension template:
* better explanation on handling soft dependencies
* correct wrong self assignment in `__init__`
> [DOC] fixes to extension templates

- skpro/distributions/base/_base.py
- skpro/distributions/tests/test_proba_basic.py
This PR adds a `plot` method to distributions, which allows users to create plots of various distribution defining functions.
For array distributions, an array of marginal subplots is created, of the corresponding plots of the marginal distributions.
The array of plots is axis aligned for comparability.
> [ENH] probability distributions: illustrative and didactic plotting functionality

- skpro/distributions/base/_base.py
Minor change that simplifies coercion in `BaseDistribution._log_pdf` and `_pdf` default.
> [ENH] simplify coercion in `BaseDistribution._log_pdf` and `_pdf` default

- docs/source/api_reference/distributions.rst
- skpro/distributions/__init__.py
- skpro/distributions/delta.py
This PR adds a delta distribution, aka constant distribution.
Requires https://github.com/sktime/skpro/pull/295 as this is a discrete distribution.
> [ENH] delta distribution

- docs/source/api_reference/distributions.rst
- skpro/distributions/__init__.py
- skpro/distributions/beta.py
Towards #22
This PR implements Beta distribution based on Scipy Adapter
> [ENH] Beta Distribution

- skpro/distributions/base/_base.py
- skpro/distributions/mixture.py
This PR upgrades the `Mixture` distribution:
* refactor to new extension interface
* support for scalar case
* tests for the above via `get_test_params`
> [ENH] `Mixture` distribution upgrade - refactor to new extension interface, support scalar case

- skpro/regression/adapters/ngboost/_ngboost_proba.py
- skpro/regression/ensemble/_ngboost.py
- skpro/survival/ensemble/_ngboost_surv.py
This adds exponential distribution to `NGBoostRegressor` and `NGBoostSurvival`.
No
Yes
> [MNT] `Exponential` dist in `NGBoostRegressor`, `NGBoostSurvival`

- build_tools/changelog.py
This PR fixes incorrectly set repository variables in the changelog generator script.
> [MNT] fix repository variables in changelog generator

- skpro/regression/enbpi.py
This PR corrects the algorithm in `EnbpiRegressor` to align with references, and adds an older reference on the same algorithm on iid data, the Jackknife-plus-Bootstrap.
The algorithm in `EnbpiRegressor` was computing quantiles on the wrong sample, which becomes apparent when comparing with both references.
> [ENH] Correct algorithm in `EnbpiRegressor`

- docs/source/api_reference/distributions.rst
- skpro/distributions/__init__.py
- skpro/distributions/gamma.py
Implements Gamma distribution.
No
Yes
> [ENH] Gamma Distribution

- README.md
- docs/source/index.rst
- extension_templates/distributions.py
- skpro/distributions/base/_base.py
- skpro/distributions/base/_delegate.py
- skpro/distributions/compose/_iid.py
- skpro/distributions/empirical.py
- skpro/distributions/mixture.py
* fixing docstring for `BaseDistribution.sample` method
* updated landing pages, references to maturing survival module
> [DOC] minor docs improvements

- skpro/domains/domains.py
- skpro/domains/tests/test_finite.py
I'm sorry. 
I did some mistake with the new and old branch. 
The easiest way was to create a new branch and open a PR. 
I will close the other ones.
> [ENH] sets module - skbase compatibility

- pyproject.toml
- skpro/registry/_lookup.py
Update `scikit-base` requirement from `<0.8.0,>=0.6.1` to `>=0.6.1,<0.9.0`
> [MNT] [Dependabot](deps): Update scikit-base requirement from <0.8.0,>=0.6.1 to >=0.6.1,<0.9.0

- README.md
- docs/source/_static/switcher.json
- docs/source/changelog.rst
- pyproject.toml
- skpro/__init__.py
Release PR for 2.3.1
* changelog
* version bump
> Release 2.3.1

- docs/source/api_reference/distributions.rst
- skpro/distributions/__init__.py
- skpro/distributions/halfnormal.py
Implements Half Normal Distribution
No
> [ENH] Half Normal Distribution

- docs/source/api_reference/distributions.rst
- skpro/distributions/__init__.py
- skpro/distributions/halfcauchy.py
Implements Half Cauchy Distribution
No
> [ENH] Half Cauchy Distribution

- skpro/model_selection/_tuning.py
Fixes #387 . Changed paramset3 to use `ConditionUncensored` instead of `CoxPH` since it doesn't seem stable on smaller datasets.
Discussion thread on #291
> [BUG] bugfix on #387 - changed paramset 3 to use `ConditionUncensored` instead of `CoxPH`

- README.md
- docs/source/_static/switcher.json
- docs/source/changelog.rst
- pyproject.toml
- skpro/__init__.py
Release PR for 2.4.0
* changelog
* version bump
> Release 2.4.0

- README.md
- docs/source/_static/switcher.json
- docs/source/changelog.rst
- pyproject.toml
- skpro/__init__.py
Release PR for 2.4.1
* changelog
* version bump
> Release 2.4.1

- README.md
- docs/source/_static/switcher.json
- docs/source/changelog.rst
- pyproject.toml
- skpro/__init__.py
Release PR for 2.4.2
* changelog
* version bump
> Release 2.4.2

- .github/workflows/wheels.yml
Copy of https://github.com/sktime/skbase/pull/349
> [MNT] release workflow: Upgrade deprecated pypa action parameter #6878

- README.md
- docs/source/_static/switcher.json
- docs/source/changelog.rst
- pyproject.toml
- skpro/__init__.py
Release PR for 2.5.0
* changelog
* version bump
> Release 2.5.0

- build_tools/changelog.py
Mirror of `sktime` https://github.com/sktime/sktime/pull/6920, due to copied code.
> [BUG] changelog utility: fix termination condition to retrieve merged PR

- skpro/utils/git_diff.py
Matches bug fix in https://github.com/sktime/sktime/pull/6862. Credit to @fnhirwa for the fix!
> [BUG] Update `skpro.utils.git_diff` to fix issue with encoding 

- README.md
Makes minor improvements to `README.md`:
* links tutorial for survival in the overview table
* adds reference to `ngboost` as popular package
* typo fixes
> [DOC] minor updates to `README.md`

- README.md
- docs/source/_static/switcher.json
- docs/source/changelog.rst
- pyproject.toml
- skpro/__init__.py
Release PR for 2.5.1
* changelog
* version bump
> Release 2.5.1

- README.md
- docs/source/_static/switcher.json
- docs/source/changelog.rst
- pyproject.toml
- skpro/__init__.py
- skpro/base/_base.py
Release PR for 2.6.0
* changelog
* version bump
> Release 2.6.0

- README.md
- docs/source/_static/switcher.json
- docs/source/changelog.rst
- pyproject.toml
- skpro/__init__.py
- skpro/base/_base.py
Release PR for 2.7.0
* changelog
* version bump
* updated project title and email
> Release 2.7.0

- .all-contributorsrc
- CODEOWNERS
- README.md
- docs/source/_static/switcher.json
- docs/source/changelog.rst
- pyproject.toml
- skpro/__init__.py
- skpro/base/_base.py
Release PR for 2.8.0
* changelog
* version bump
> Release 2.8.0

- CODEOWNERS
Updates the CODEOWNERS file:
* @yarnabrina removed upon request
* @achieveordie removed as inactive
* @felipeangelimvieira added as new core dev
> [MNT] Update CODEOWNERS file

- extension_templates/distributions.py
- extension_templates/regression.py
- extension_templates/survival.py
This PR adds an instruction preamble to each current extension template on how to use them.
> [DOC] extension templates: instruction preamble

- README.md
- docs/source/_static/switcher.json
- docs/source/changelog.rst
- pyproject.toml
- skpro/__init__.py
Release PR for 2.9.0
* changelog
* version bump
> Release 2.9.0

- .github/workflows/test.yml
Removes the compromised `tj-actions` GH action and replaces it by custom code.
See https://github.com/sktime/sktime/issues/7988
> [MNT] remove `tj-actions`

- docs/source/changelog.rst
Fixes a typo in the changelog.
> [DOC] fix typo in changelog

- skpro/registry/_lookup.py
- skpro/utils/_maint/tests/test_show_versions.py
Mirror fix of https://github.com/sktime/sktime/pull/7679
> [BUG] fix `all_objects` lookup in case a tag is used that is not scitype specific

- skpro/metrics/_classes.py
- skpro/metrics/base.py
Part 2 of https://github.com/sktime/skpro/pull/537
> [ENH] sync probabilistic metrics with `sktime`, part 2

- docs/source/_static/switcher.json
- docs/source/changelog.rst
- pyproject.toml
- skpro/__init__.py
Release PR for 2.9.1
* changelog
* version bump
> Release 2.9.1

- README.md
2.9.1 - update version number in README
> 2.9.1 - update version number in README

- skpro/benchmarking/evaluate.py
minor docstring fixes of issues flagged up through https://github.com/sktime/skpro/pull/543
> [DOC] minor docstring fixes

- .all-contributorsrc
- docs/source/api_reference/distributions.rst
- skpro/distributions/__init__.py
- skpro/distributions/discrete_truncated.py
- skpro/distributions/hurdle.py
- skpro/distributions/left_truncated.py
- skpro/distributions/truncated.py
Partially adresses #554 
Adds a left truncated and hurdle distribution.
No.
* Correctness of implementation.
* Design choice of using `BaseDistribution` for base class for both distributions. They should perhaps classify as something else, like transform?
No new tests.
Still WIP, just opening a draft PR to discuss design choices before opening a full.
See here …
> [ENH] Adds `Hurdle` and `LeftTruncatedDiscrete` distributions

- README.md
- docs/source/_static/switcher.json
- docs/source/changelog.rst
- pyproject.toml
- skpro/__init__.py
Release PR for 2.9.2
* changelog
* version bump
> Release 2.9.2

- skpro/distributions/hurdle.py
- skpro/distributions/truncated.py
Moves the epsilon fix from Hurdle to truncated instead
> [ENH] Moves eps fix

- pyproject.toml
updates `numpy` bound to `numpy<2.4`
> [MNT] update `numpy` bound to `numpy<2.4`

- skpro/regression/binned/_sklearn_bin_regressor.py
Minor improvements to the docstring of `HistBinnedProbaRegressor`:
* usage example
* formatting
> [DOC] improved docstring for `HistBinnedProbaRegressor`

- README.md
- docs/source/_static/switcher.json
- docs/source/changelog.rst
- pyproject.toml
- skpro/__init__.py
Release PR for 2.9.4
* changelog
* version bump
> Release 2.9.4

- skpro/regression/linear/_glm.py
Temporary skip for #594 until resolved.
> [MNT] temporarily skip sporadic `GLMRegressor` test failure

- extension_templates/survival.py
minor docstring formatting in survival predictor extension template
> [DOC] minor docstring formatting in survival predictor extension template

- skpro/regression/residual.py
minor documentation improvements - docstring formatting
> [DOC] minor documentation improvements
